### ISSUE TITLE
[BUG] Sidebar dropwown not working

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#274] opened 2022-10-27 12:56 UTC
### Describe the bug

 The sidebar dropdown not working
![image](https://user-images.githubusercontent.com/44284877/198293652-6aa5898c-4165-4a8a-b12b-dbe1f43d3750.png)
when we click on this nav-item nothing happens

### To Reproduce

Click on the Sidebar > learn. dropdown not working

### Expected Behavior

Like this: the drop should be displayed 
![image](https://user-images.githubusercontent.com/44284877/198293966-fe1e47ab-9d61-48c4-aadc-4e30b9151f37.png)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by avezqureshi14** [comment] 2022-10-27 13:10
Can you assign this to me

**Comment by kabir0x23** [comment] 2022-10-27 13:13
Hey @avezqureshi14 

I have updated the desc for the issue.
 
I have assigned this issue to you.

**Comment by Rahul-Palamarthi** [comment] 2022-10-31 04:54
Can you assign this issue to me

**Comment by kabir0x23** [comment] 2022-10-31 06:58
I Have assigned this issue to you

If you need any help let us know 

Thank You

**Comment by Rahul-Palamarthi** [comment] 2022-10-31 10:53
unable to download node_modules through the command "npm install"

**Comment by Rahul-Palamarthi** [comment] 2022-10-31 11:14
I fingured it out and now i will be working on the issue

**Comment by kabir0x23** [comment] 2022-10-31 11:22
> I figured it out and now I will be working on the issue

Awesome 🚀

**Comment by Rahul-Palamarthi** [comment] 2022-10-31 14:13
can we use className and CSS files  for styling??

**Comment by kabir0x23** [comment] 2022-10-31 14:20
> can we use className and CSS files for styling??

Okay you can use css

**Comment by Rahul-Palamarthi** [comment] 2022-11-01 05:10
I have finished my code and yet to commit but I am facing the issue during commit. Can you help me?
![Screenshot (95)](https://user-images.githubusercontent.com/87606332/199163404-d45fbb9c-840e-4b27-ac74-61bdf25bec42.png)

**Comment by kabir0x23** [comment] 2022-11-01 05:15
> I have finished my code and yet to commit but I am facing the issue during commit. Can you help me? ![Screenshot (95)](https://user-images.githubusercontent.com/87606332/199163404-d45fbb9c-840e-4b27-ac74-61bdf25bec42.png)

Those are undefined variables, you can do comments or remove those, it will work

**Comment by Rahul-Palamarthi** [comment] 2022-11-01 05:23
Yes, The problem is solved

**Comment by kabir0x23** [comment] 2022-11-01 05:24
> Yes, The problem is solved

Awesome

**Comment by Rahul-Palamarthi** [comment] 2022-11-01 05:32
I also made a PR to the main branch

**Comment by Rahul-Palamarthi** [comment] 2022-11-01 05:33
I also made a PR

**Comment by kabir0x23** [comment] 2022-11-01 05:40
hey @Rahul-Palamarthi there are issues in navbar

now navbar is not working

**Comment by Rahul-Palamarthi** [comment] 2022-11-01 05:54
You can remove Navbar.jsx

Both the laptop and mobile design is in single component Navbars.jsx

**Comment by kabir0x23** [comment] 2022-11-01 05:56
> You can remove Navbar.jsx
> 
> Both the laptop and mobile design is in single component Navbars.jsx

with the navbars it is not working

onhovering, it is causing issues (we are not able to react at dropdown menu) give a look

**Comment by kabir0x23** [comment] 2022-11-01 05:57
> You can remove Navbar.jsx
> 
> Both the laptop and mobile design is in single component Navbars.jsx

you can do changes in the same Branch and push the code

**Comment by Rahul-Palamarthi** [comment] 2022-11-01 06:04
In desktop design the menu will only show when hover on the menu.
so they should show on click also in Desktop version??

**Comment by Rahul-Palamarthi** [comment] 2022-11-01 06:06
ok I figured the problem I will the looking at the issue.

**Comment by kabir0x23** [comment] 2022-11-01 06:09
> ok I figured the problem I will the looking at the issue.

Okay 🚀

**Comment by Rahul-Palamarthi** [comment] 2022-11-01 06:39
In Desktop version when we hover on the element, then the options will appear but when we click on the element then the options will disappear??

**Comment by kabir0x23** [comment] 2022-11-01 06:42
> In Desktop version when we hover on the element, then the options will appear but when we click on the element then the options will disappear??

yes, absolutely

**Comment by Rahul-Palamarthi** [comment] 2022-11-01 06:51
Ok I will be working on it

**Comment by Rahul-Palamarthi** [comment] 2022-11-01 09:00
I have updated the code and it is responsive in both desktop and mobile version. Hope you like it 🧑‍💻

**Comment by kabir0x23** [comment] 2022-11-01 10:07
> I have updated the code and it is responsive in both desktop and mobile version. Hope you like it 🧑‍💻

Great, we will review the PR and merge very soon. until then/If you are looking to contribute more to the open-source, then you can give a look at other open issues or can create issues.

Thank you 😄.

**Closed** 2022-11-01 10:32 UTC
Labels: ✨ goal: improvement, 🛠 goal: fix, 🤩 status : Up for Grab, 🟥 priority: critical, hacktoberfest
