### ISSUE TITLE
[FEATURE] Create a page to showcase our open-source projects

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#164] opened 2022-10-11 06:50 UTC
### Detailed description

Create a page to showcase our open-source projects

open-source projects list:
https://github.com/thecyberworld/Thecyberhub.org

### Context

.

### Additional information

If you need any help or have any doubts or questions let us know.

Thank you 😄.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SabujGolui** [comment] 2022-10-11 06:54
I'll like to work on it

**Comment by kabir0x23** [comment] 2022-10-11 06:59
> I'll like to work on it

Nice, I am assigning this issue to you.

**Comment by abdullmustyy** [comment] 2022-10-13 13:46
Hi, @kabir0x23 
I have created a page to show open-source projects, but I need to make some clarifications before I proceed to add the content. Please check below for a video illustration and extra details.

[New Recording - 10_13_2022, 2_32_23 PM.webm](https://user-images.githubusercontent.com/87391935/195612385-77da5707-ec13-48e8-bcf5-ebaa021338e1.webm)

**_Questions:_**

- The place I have put the link to the open-source page. Is it okay with you?
- The open-source projects on your repo are the ones I should display, right?

**Comment by kabir0x23** [comment] 2022-10-13 13:50
Hey @abdullmustyy , this looks good

> - The place I have put the link to the open-source page. Is it okay with you?
- yes, looks good over there 
> - The open-source projects on your repo are the ones I should display, right?
- yes, right

**Comment by SabujGolui** [comment] 2022-10-13 13:59
I have added a seperate page for the project section so that it's visible in navber and visiters can visit easily

**Comment by SabujGolui** [comment] 2022-10-13 14:00
Pls give some of your project name and discription so that I can add these in a card from in this page

**Comment by kabir0x23** [comment] 2022-10-13 14:00
> Pls give some of your project name and discription so that I can add these in a card from in this page

Hello @SabujGolui , wait a sec here

**Comment by kabir0x23** [comment] 2022-10-13 14:01
> I have added a seperate page for the project section so that it's visible in navber and visiters can visit easily

That's Nice

**Comment by SabujGolui** [comment] 2022-10-13 14:02
The issue is assigned to me, right?

**Comment by kabir0x23** [comment] 2022-10-13 14:02
> Pls give some of your project name and discription so that I can add these in a card from in this page

hey @SabujGolui, you can add dummy data in descriptions, we will add those later

**Comment by kabir0x23** [comment] 2022-10-13 14:04
@abdullmustyy , hey
We already assigned this issue to @SabujGolui 
We can do one thing

Once @SabujGolui sends the pr, we will merge it, and after that, you can add that page link to the homepage open-source button

**Comment by kabir0x23** [comment] 2022-10-13 14:04
@abdullmustyy and also you can create a new feature req of that open-source button., i will assign it to you.

**Comment by abdullmustyy** [comment] 2022-10-13 14:15
Okay, that will be great @kabir0x23 

I'm so sorry for not confirming your state with the contribution before jumping on it, @SabujGolui

**Closed** 2022-10-14 07:21 UTC
Labels: 🟧 priority: high, ⭐ goal: addition, 🏁 status: ready for dev, good first issue, hacktoberfest
