### ISSUE TITLE
[BUG] Today's Events logic bug

### ISSUE THREAD

**Issue by x-devNerd-x** [thecyberworld/thecyberhub.org#190] opened 2022-10-15 18:47 UTC
### Describe the bug

If there are no today's events
Today's events are still there
![image](https://user-images.githubusercontent.com/44284877/196005865-72f40e71-58d2-45d2-9518-77312ad53272.png)

![image](https://user-images.githubusercontent.com/115712204/196003122-3f75d925-1d05-4e97-9bdf-1a4822ab50b3.png)

### To Reproduce

https://www.thecyberhub.org/events

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ruchita-01** [comment] 2022-10-15 20:03
Issue Resolved
Kindly check below PR
https://github.com/thecyberworld/thecyberhub.org/pull/191

**Comment by kabir0x23** [comment] 2022-10-15 20:19
> Issue Resolved Kindly check below PR #191
(#186 is got resolved with #191 )

@Ruchita-01 

The issue is not getting resolved with this PR #191.  
because today's events are outside of the map/loop functions
so where there are no events today, so we want to display that heading too

**Comment by kabir0x23** [comment] 2022-10-15 20:20
If you want to work om this issue, let us know, and we will assign this issue to you,

Thank you.

**Comment by ihtishamKhan** [comment] 2022-10-16 08:18
I want to work on this issue, Please assign this issue to me

**Comment by kabir0x23** [comment] 2022-10-16 08:26
Awesome, I am assigning this issue to you.

**Comment by code-knayam** [comment] 2022-10-16 08:55
Issue resolved. Please check https://github.com/thecyberworld/thecyberhub.org/pull/193

**Comment by ihtishamKhan** [comment] 2022-10-16 09:05
The issue was assigned to me, I was working on that. How come? @kabir0x23 @code-knayam

**Comment by kabir0x23** [comment] 2022-10-16 09:37
yes send you PR, I haven't merged that PR till now

**Comment by ihtishamKhan** [comment] 2022-10-16 09:38
Thank you @kabir0x23

**Comment by code-knayam** [comment] 2022-10-16 10:19
> The issue was assigned to me, I was working on that. How come? @kabir0x23 @code-knayam 

Usually the first PR resolving the issue is referenced. 😁

**Comment by ihtishamKhan** [comment] 2022-10-16 10:26
> > The issue was assigned to me, I was working on that. How come? @kabir0x23 @code-knayam
> 
> Usually the first PR resolving the issue is referenced. 😁

Correct but I think it's in case of the issue was not assigned to either one
I am worried that the first developer works on an issue let's say for 2 days, and the other one also starts working on the same issue without informing the first one. The result will be a waste of 2 days. Thoughts from your side are welcome if I am wrong

**Closed** 2022-10-16 17:01 UTC
Labels: 🏁 status: ready for dev, 🛠 goal: fix, 🐛 bug, 🟥 priority: critical, 💻 aspect: code, good first issue, hacktoberfest
